In [3]:
import numpy as np

In [4]:
np.__version__

'1.13.3'

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.random.normal(10,100)

-55.65614132145757

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x.ndim

1

In [9]:
X = np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
x[0]

0

In [11]:
X[(2,2)]

12

In [12]:
X[2,2]

12

In [13]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [14]:
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
X[:,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [16]:
X[:2,::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [17]:
X[0,:].dtype

dtype('int64')

In [18]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [20]:
subX[0,0] = 100

In [21]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [22]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [23]:
subXX = X[:2,:3].copy()

In [24]:
subXX

array([[100,   1,   2],
       [  5,   6,   7]])

In [25]:
subXX[0,0] = 1000

In [26]:
subXX

array([[1000,    1,    2],
       [   5,    6,    7]])

In [27]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [28]:
x.shape

(10,)

In [29]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
x.reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [32]:
x.shape

(10,)

In [33]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
x.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [35]:
x.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [36]:
A = np.array([[1,2,3],[4,5,6]])

In [37]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [39]:
z = np.array([4,4,4])

In [40]:
np.concatenate([A,z.reshape(1,-1)])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 4, 4]])

In [41]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.vstack([A,z])

array([[1, 2, 3],
       [4, 5, 6],
       [4, 4, 4]])

In [43]:
B = np.full((2,2),100)

In [44]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [45]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
x1,x2,x3 = np.split(x,[3,7])

In [47]:
x1

array([0, 1, 2])

In [48]:
x2

array([3, 4, 5, 6])

In [49]:
x3

array([7, 8, 9])

In [50]:
x1,x2 = np.split(x,[5])

In [51]:
x1

array([0, 1, 2, 3, 4])

In [52]:
A = np.arange(16).reshape((4,4))

In [53]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
A1,A2 = np.split(A,[2])

In [55]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [56]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
A3,A4 = np.split(A,[2],axis=1)

In [58]:
A3

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [59]:
np.vsplit(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [60]:
x,y=np.hsplit(A,[-1])

In [61]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [62]:
y[:,0]

array([ 3,  7, 11, 15])

In [63]:
ind = [3,5,8]

In [64]:
x = np.arange(10)

In [65]:
x[ind]

array([3, 5, 8])

In [66]:
ind = np.array([0])